### create report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "price": 15000,
    "make": "Kia",
    "model": "Forte",
    "year": 2016,  
    "lng": -92.2206902,
    "lat": 32.8354778, 
    "mileage": 200000
}


### patch report
PATCH http://localhost:3000/reports/1
Content-Type: application/json

{
    "approved": true
}

### get estimate
GET http://localhost:3000/reports?make=Honda&model=Accord&year=2018&lng=-97.2206902&lat=32.8354778&mileage=5